### ISSUE TITLE
Can't Launch Exhibitera Apps in stand-alone mode: "GET /definitions//load HTTP/1.1" 404 Not Found

### ISSUE THREAD

**Issue by David-S-Morgan** [Cosmic-Chatter/Exhibitera#12]
Hi,

I'm running into a bug when using Exhibitera Apps in standalone mode.  When I go to "Launch app" It appears the definition json file is not being referenced when it is to be loaded (last line in output below).
```
INFO:     127.0.0.1:36262 - "POST /files/thumbnailVideoFromFrames HTTP/1.1" 200 OK
INFO:     127.0.0.1:36278 - "GET /definitions/media_player/getAvailable HTTP/1.1" 200 OK
INFO:     127.0.0.1:46732 - "GET /app.html HTTP/1.1" 200 OK
INFO:     127.0.0.1:46742 - "GET /css/bootstrap_5_3/bootstrap.min.css HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:46732 - "GET /js/app.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:46744 - "GET /js/jquery-3.6.1.min.js HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:46770 - "GET /js/platform.js HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:46754 - "GET /js/bootstrap_5_3/bootstrap.bundle.min.js HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:46732 - "GET /js/exhibitera_app_common.js HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:46732 - "GET /getDefaults HTTP/1.1" 200 OK
INFO:     127.0.0.1:46732 - "GET /definitions//load HTTP/1.1" 404 Not Found
```
The last command should probably be something like "GET /definitions/<SOMEUUID>.json/load.  Note that the preview in the setup screen does work, just the actual launching of the app fails.  I noted this with both InfoStation and Media Player, and have not tested the others.

**Comment by David-S-Morgan** [comment]
Yup, it turned out to be a [PEBCAK](https://en.wiktionary.org/wiki/PEBCAK) error -- I selected the definition, but I didn't actually save the settings after selecting the correct definition.  (From a UI standpoint, it would be good if there was some indication that there has been a config change that needs to be saved when you try to launch the app.)

Sorry for the false alarm!

**Comment by forceflow1049** [comment]
Glad it was an easy fix! I agree that the save button should appear only once you have selected something.
