### ISSUE TITLE
Exhibitera_Apps throws exception - ModuleNotFoundError: No module named 'PyDMXControl'

### ISSUE THREAD

**Issue by David-S-Morgan** [Cosmic-Chatter/Exhibitera#2]
(I'm not sure if you're ready yet for people to test the beta, so please let me know if I should hold off until the official release. Thanks!)

Trying to run Exhibitera_Apps latest beta fails with:

```
Traceback (most recent call last):
  File "Exhibitera_Apps.py", line 23, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "helper_dmx.py", line 7, in <module>
ModuleNotFoundError: No module named 'PyDMXControl'
[279332] Failed to execute script 'Exhibitera_Apps' due to unhandled exception!
```

Ubuntu 22.04, both Python3.10 (default repo) and Python3.12 (installed from PPA).

**Comment by forceflow1049** [comment]
Hi @David-S-Morgan, are you trying to run the scripts directly or build the binary? Both should work—the binary builds successfully for me on Ubuntu 20.04. A couple things to note:

- You can find OS-specific build scripts in the new exhibitera/build/ directory
- There are separate `requirements.txt` files for Apps and Hub 
- Python 3.12 is the target platform, although I suspect it will work fine on 3.10+

The Exhibitera 5 beta should be ready to play with—we have been final testing it on our production environment the last couple of weeks. Only a couple of small issues to resolve before final release.

**Comment by David-S-Morgan** [comment]
Hi @forceflow1049, I built the binary using your build scripts, and that completed without error.  

I just set up a fresh Ubuntu 22.04 VM and the apps binary builds and runs successfully there under Python 3.10, so it must be something in my environment that is causing the issue -- I'll let you know if I figure it out.

**Comment by forceflow1049** [comment]
Glad it's working for you!
