### ISSUE TITLE
/system/ping not backwards compatible between ID and UUID

### ISSUE THREAD

**Issue by alexaverill** [Cosmic-Chatter/Exhibitera#22]
I was working on setting up an integration with the system/ping endpoint and have come across a couple small issues, that I think might just need to be documentation updates. 

I was trying implementing a simple ping between a frontend application and Hub. I setup a exhibit definition and component in Hub. 
Following the documentation I have my application sending the following PING message:
```json
{"currentInteraction":false,"group":"Default","helperAddress":"","id":"Generic APp","permissions":{"audio":false,"refresh":false,"restart":false,"shutdown":false,"sleep":false}}``` 
```

This results in:

```
{
  "success": false,
  "reason": "Request missing 'uuid' field."
}
```
It looks like in the endpoint itself there is a callout that there was a goal to allow ID's for legacy support
```python
@app.post("/system/ping")
async def handle_ping(data: dict[str, Any], request: Request):
    """Respond to an incoming heartbeat signal with ahy updates."""

    if "uuid" not in data:
        response = {"success": False,
                    "reason": "Request missing 'uuid' field."}
        return response

    ex_exhibit.update_exhibit_component_status(data, request.client.host)

    if "uuid" in data:
        # Preferred way from Exhibitera 5
        component = ex_exhibit.get_exhibit_component(component_uuid=data['uuid'])
    else:
        # Legacy support
        component = ex_exhibit.get_exhibit_component(component_id=data['id'])

    dict_to_send = component.config.copy()
    if len(dict_to_send["commands"]) > 0:
        # Clear the command list now that we are sending
        component.config["commands"] = []
    return dict_to_send
```
However that first if statement short circuits if there isn't a UUID. Is that the expected behavior? 
If it is, that makes sense, just might be worth updating the documentation (If there is an easy way for me to help with that let me know, I am happy to help out)

If its not intended what should the expected behavior be? 

If I do pass in the UUID of the sample exhibit I setup and pass along this JSON object I do get the expected response
```json
{"currentInteraction":false,"group":"Default","helperAddress":"","id":"null","uuid":"298e2b46-c4f0-46c4-ba69-ffc67243ef59","permissions":{"audio":false,"refresh":false,"restart":false,"shutdown":false,"sleep":false}}
```

**Comment by forceflow1049** [comment]
Hi @alexaverill, this is a good catch—I think you're right that this is a documentation issue mainly. Early in development for Exhibitera 5, there was the goal of maintaining backwards compatibility to v4. But the decision to implement a robust user account system (a top request) ended up making that impossible. The [download page](https://exhibitera.org/download/) notes that Hub 5 is only compatible with Apps 5 or above, so I think we're safe to remove the outdated functionality.

I've changed the code in branch Dev_5.2 to read: 

```python
@app.post("/system/ping")
async def handle_ping(data: dict[str, Any], request: Request):
    """Respond to an incoming heartbeat signal with ahy updates."""

    if "uuid" not in data:
        response = {"success": False,
                    "reason": "Request missing 'uuid' field."}
        return response

    ex_exhibit.update_exhibit_component_status(data, request.client.host)

    component = ex_exhibit.get_exhibit_component(component_uuid=data['uuid'])
    dict_to_send = component.config.copy()

    if len(dict_to_send["commands"]) > 0:
        # Clear the command list now that we are sending
        component.config["commands"] = []
    return dict_to_send
```

The group field actually doesn't do anything in Hub 5 either—component membership in groups is now managed by Hub rather than by the individual apps. So I have updated the docs to reflect that, too.
