### ISSUE TITLE
code change to add a looping function for media browser

### ISSUE THREAD

**Issue by Code-Bagi** [Cosmic-Chatter/Exhibitera#23]
starting at line 5 in the media_browser.js file, you will see this: 

```javascript 

function changePage (val) {
  switch (val) {
    case 0:
      currentPage = 0
      break
    case 1:
      // Calculate if there are more cards to show
      if ((currentPage + 1) * cardsPerPage < spreadsheet.length) {
        currentPage += 1
      }
      break
    case -1:
      currentPage -= 1
      if (currentPage < 0) {
        currentPage = 0
      }
      break
    default:
  }

```

The addition to a loop here provides ease for a user to get back to the first page of the slideshow once they have reached the end. The change in code to make this happen would look like this: 

```javascript 

function changePage (val) {
  switch (val) {
    case 0:
      currentPage = 0
      break
    case 1:
      currentPage += 1
      if (currentPage * cardsPerPage >= spreadsheet.length) {
        currentPage = 0
      }
      break
    case -1:
      currentPage -= 1
      if (currentPage < 0) {
        currentPage = Math.floor((spreadsheet.length - 1 / cardsPerPage)) 
      }
      break
    default:
  }
```

**Comment by forceflow1049** [comment]
Hi @Code-Bagi, thanks for the suggestion! I think this change makes sense, but can we think of any instances in which this would not be desirable behavior? If so, this behavior could be an option toggled during setup.

**Comment by alexaverill** [comment]
I think having this as the default would make sense, but having a toggle to turn it off would help incase someone didn't want it for whatever reason

**Comment by David-S-Morgan** [comment]
Somewhat related to this issue, it would be good to hide the arrows in Media Browser if there is only one page of content.  (Not sure if it's worth a separate issue, but I'm happy to open one if so.)

**Comment by forceflow1049** [comment]
Agreed, @David-S-Morgan, that makes sense. I will roll that into the looping fix when I get the chance.

**Comment by forceflow1049** [comment]
Both this issue and the suggestion from @David-S-Morgan are included in https://github.com/Cosmic-Chatter/Exhibitera/commit/b8c5e94cd0eec44311dc8c6ceee6e27885f2e686
