### ISSUE TITLE
MediaBrowser: Aborting video playback before end results in attractor not showing up after timeout

### ISSUE THREAD

**Issue by David-S-Morgan** [Cosmic-Chatter/Exhibitera#32]
I noticed that if I tap to abort a video before it ends, the attractor ceases to show up after the timeout.  I suspect the 'ended' event is not firing in that case, so 

`document.getElementById('mediaLightboxVideo').addEventListener('ended', (event) => {
  resetActivityTimer()
  videoPlaying = false
})`

at the end of media_browser.js isn't called.  Not sure though which event would be triggered in this case.

**Comment by David-S-Morgan** [comment]
Adding

`resetActivityTimer()`
`videoPlaying = false`

to `hideMediaLightBox` does seem to take care of the issue, and in my brief testing doesn't seem to break anything else.

**Comment by forceflow1049** [comment]
Fixed in https://github.com/Cosmic-Chatter/Exhibitera/commit/b8c5e94cd0eec44311dc8c6ceee6e27885f2e686
