### ISSUE TITLE
Issue in MediaBrowser when using background image in Firefox

### ISSUE THREAD

**Issue by David-S-Morgan** [Cosmic-Chatter/Exhibitera#45]
Hi,

I noticed a weird issue when using media browser.  If I set an image as the background, then the content does not show up, but for some reason the filter (which I am not utilizing) does.  Using a gradient or solid color, everything is fine.  This appears to only happen with Firefox, and previously I'd only noticed it when using a private window.  Now it seems to happen even from a regular window.  I did try firefox on different computers (and my phone) with the same result.  I haven't tried creating a new media_browser config from scratch, but will try that.  

I'm currently using 5.1 (with a few minor changes that I don't think would have affected this, but I can also try 5.2 fresh if you think it might be something that's fixed already.

I'm including screenshots of the inspector from Firefox showing the two cases, in case it might be helpful.  FYI, this isn't urgent for me.

(Items that are collapsed are basically identical between the two cases)
Case where it works with a gradient:
![Background-is-gradient](https://github.com/user-attachments/assets/b2703d4a-d780-426c-8b17-e7f348eb1e00)

Case where it doesn't work with an image:
![Background-is-image](https://github.com/user-attachments/assets/b960d88d-e70d-478d-af72-82bbad40e8f0)

**Comment by forceflow1049** [comment]
@David-S-Morgan I can reproduce this issue in 5.1, but not 5.2, so upgrading Apps should resolve this for you!

<img width="1504" alt="image" src="https://github.com/user-attachments/assets/e33447a0-c4dd-4f35-ad34-c6cf769a72d2" />
