### ISSUE TITLE
Word Cloud Input should support keyboard entry

### ISSUE THREAD

**Issue by alexaverill** [Cosmic-Chatter/Exhibitera#6]
I think there would be some value to adding keyboard support to the Word Cloud Input application. It would add some extra versatility for a museum that doesn't have a touchscreen available, and would be helpful for testing inputs. 
 
This is something I was going to implement over the next few weeks

**Comment by forceflow1049** [comment]
This is a smart idea that would make a nice contribution. One thing to consider—when using a touchscreen in Windows, Linux, and iOS, touching a text field beings up the software keyboard. That might open up opportunities to escape kiosk mode. So could we implement it in a way that doesn't expose an active text field? 

Also, if using a hardware keyboard, the onscreen keyboard should probably be hidden. So maybe this is a toggle during setup?

**Comment by alexaverill** [comment]
We can do it through event listeners, and just inject the user inputs into the text field., the other thing we'll need to consider is a keyboard would also allow for a way to alt+tab or ctrl+alt+delete, so we might also need to consider a more comprehensive app launcher that intercepts keyboard input to avoid that issue. I'll give that end some thought as well. This might end up being a multi-part adventure.

**Comment by forceflow1049** [comment]
An initial step might be to assume users who want hardware input will use a kiosk-specific keyboard without those keys. That would provide the option for a hardware keyboard for more advanced users to start.

**Comment by forceflow1049** [comment]
Marking this as complete since the PR has been accepted.
